apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{.Values.ns}}
type: Opaque
data:
  BROKER_USER: {{ .Values.broker.user | b64enc }}
  BROKER_PASS: {{ .Values.broker.pass | b64enc }}