apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.ns}}
  name: server
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
  - port: {{ .Values.server.internal_port }}
    targetPort: {{ .Values.server.external_port }}
